# Generated by Django 4.1.4 on 2023-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
